### ISSUE TITLE
Remove old db layer completely

### ISSUE THREAD

**Issue by freen** [RNGR/directus6#228]

**Comment by benhaynes** [comment]
Hey @WellingGuzman – @jel-massih said that this is complete, can you confirm that the old DB layer is not used anywhere, and that's it is removed from Directus?

**Comment by benhaynes** [comment]
@WellingGuzman Is this now complete or is there more to do? I'm sure some testing is needed...

**Comment by WellingGuzman** [comment]
I believe it's done, I checked for any reference to old db, and did a quick test and all the pages was working and there's not error. Having in mind that the Old DB object does not exists anymore.

There's no more reference to the old db.
