### ISSUE TITLE
Redirect to original URL when logging in

### ISSUE THREAD

**Issue by benhaynes** [RNGR/directus6#351]
When you try to access a specific page URL within Directus but you are not logged in, it currently takes you to the last page you were on when you logged out. Instead, you should be taken to the page you were trying to access:

Logged in: Looking at page A
Logoff
Login: Takes you to page A
Logoff
Attempt to go to page B
Login: SHOULD take you to page B, not A

Talk to Ben if this is unclear.

**Comment by benhaynes** [comment]
@WellingGuzman This seems to be working, but the original (no redirect) code doesn't.

Logging in directly from login page (no redirect URL) should go to **directus_users.last_page** – so the user continues where they left off. Currently it always goes to the *users* page.

**Comment by WellingGuzman** [comment]
@benhaynes that's odd, I'd check this out again, I tested this one a lot, and the fallback list is like this.

1. If there's a redirect uses redirect url
2. if there's not redirect url, use last_page url.
3. If there's not last_page use default page, "users"

I'd take a look, again.

**Comment by benhaynes** [comment]
Grat fix!
