### ISSUE TITLE
Hiding fields in settings should hide them from the item listing page

### ISSUE THREAD

**Issue by jmsrngr** [RNGR/directus6#448]
For example, if I hide a field for a checkbox in Settings, all users who have that field shown as a column on that table should not see it anymore.

**Comment by WellingGuzman** [comment]
@benhaynes I merged this [PR#634](https://github.com/RNGR/directus6/issues/634) now when the hidden_input is true on a column it would be hidden from the table listing. let me know if this is exactly what you were referring to with this issue.

**Comment by benhaynes** [comment]
@WellingGuzman This seems to partially work, but there are two issues:

1. The hidden column should disappear from the listing page column select dropdown too  (clicking the gear in the header)
2. When changing the listing page column select dropdown (clicking the gear in the header) the visible columns should change immediately – currently you have to refresh the page. This was working before.

![screen shot 2015-02-07 at 10 35 52 am](https://cloud.githubusercontent.com/assets/522079/6092634/369bb40c-aeb5-11e4-9aa9-f94a8f8be173.png)

**Comment by WellingGuzman** [comment]
@benhaynes correct me if I'm wrong, but I believe this used to work back when the page was auto reloaded the browser after a save, this would need extra tweak probably. But I'd take a look back to when this used to work so I'm sure what's the issue.

**Comment by WellingGuzman** [comment]
@benhaynes nevermind, it was about the realoading.

**Comment by benhaynes** [comment]
Works perfectly, thanks!
