### ISSUE TITLE
Tracked "Build" of Directus

### ISSUE THREAD

**Issue by benhaynes** [RNGR/directus6#459]
Alongside the full "developer" codebase of Directus, there should be a _build_ of the current version with the following qualities:

*Does not require composer or other command line setup
*Compiles CSS and JS into single files when possible
*Minifies and compresses all files when possible
*Strips out all unused files (LESS, etc)
*Has a lightweight filesize... ideally less than 1MB
*Uploading files and running installation file is all that's required

**Comment by benhaynes** [comment]
May want to add or remove a file or path from the build scripts – but otherwise this is complete.

Right @WellingGuzman ?

**Comment by WellingGuzman** [comment]
Exactly @benhaynes
