### ISSUE TITLE
Clicking the table name under settings toggles all permissions

### ISSUE THREAD

**Issue by benhaynes** [RNGR/directus6#493]
From within *Settings > Permissions > Group*, when you click on a table name (on the left) it toggles all permissions for that table on/off (full permissions, to none). If *partial* permissions exist and you click the table name it would go to Full Permissions.

**Comment by benhaynes** [comment]
This does not work if the permission has never been clicked (it's new) – only if it has a record within directus_privileges. It needs to also toggle all permissions on if they don't exist yet...

**Comment by benhaynes** [comment]
@jel-massih Hey Jason, did you close this by accident? I believe the issue is still present...

If you click the row's title before any permissions have been set it does not work properly. Also, it seems to save an abridged set of permissions (either big or normal, but not both).

**Comment by WellingGuzman** [comment]
@benhaynes Is this something it shouldn't happens or the problem is that is not setting both (big and normal) permission when it has to?

**Comment by benhaynes** [comment]
If I add a new table to the database directly, then go to Settings > Permissions and click the table name (to toggle all table permissions) I get the following error:

![screen shot 2015-03-08 at 2 42 46 pm](https://cloud.githubusercontent.com/assets/522079/6547635/a71bd724-c5b3-11e4-8621-c07c63d9c442.png)

**Comment by benhaynes** [comment]
Closed indeed!
