### ISSUE TITLE
Add hard-delete policy option

### ISSUE THREAD

**Issue by benhaynes** [RNGR/directus6#496]
## Soft-Delete Policy (Exists)
Currently Directus has a soft-delete policy (by design) that only allows items to be flagged as "deleted" in an active/status column. This gives a hierarchical system of status that is customizable by project:

**Status column values:** (default column name is "active") 
* 0 = deleted (not shown in directus system)
* 1 = active/live/published
* 2 = inactive/draft

**/api/config.php** – *Define required status parameters*
```
define('STATUS_DELETED_NUM', 0); // status INT value of deleted items (not shown in Directus)
define('STATUS_ACTIVE_NUM', 1); // status INT value of active items (all other status items are grayed out)
define('STATUS_COLUMN_NAME', 'active');  //  adjustable global name for status column, defaults to active
```

**/api/configuration.php** – *Extend with optional status parameters*
```
  'statusMapping' => array(
    '0' => array(
      'name' => 'Deleted',
      'color' => '#C1272D',
      'sort' => 3
    ),
    '1' => array(
      'name' => 'Live',
      'color' => '#5b5b5b',
      'sort' => 1
    ),
    '2' => array(
      'name' => 'Draft',
      'color' => '#bbbbbb',
      'sort' => 2
    )
  )
```

## Hard-Delete Policy (New Feature)
We'll need to "truly delete" certain items within Directus for projects that require it. This will require adding some new logic into the API – and this should be done with care to avoid the ability to maliciously take advantage of the DELETE feature. We would add a FOURTH/FIFTH state to the DELETE column of the permissions GUI. So the toggle would go:

* No Permission
* Soft-Delete
* Big Soft-Delete
* Hard-Delete 
* Big Hard-Delete ;)

![screen shot 2014-12-05 at 11 16 30 am](https://cloud.githubusercontent.com/assets/522079/5318748/a3861a70-7c70-11e4-8f5b-e71b3364c81b.png)

**Comment by benhaynes** [comment]
@WellingGuzman The "magic owner column" is saved in the `user_create_column` (previously called: magic_owner" I believe) field within `directus_tables`. If a table has a column to track which user created its records, then it should be saved here. This is how we enforce the BIG permissions (BIGedit, BIGview, etc). 

* Edit permission: Means that you can edit **only your items** (if column saved under `directus_tables.user_create_column` has your user ID)
* BIGedit permission: Means that you can edit **any users items**

I think it'd be good to switch the naming of these permissions since they seem counterintuitive now. This might be better:

* **AuthorEdit, AuthorDelete, AuthorView** for only items you've created
* **Edit, Delete, View** for any/all items

If table permissions are set to EDIT (not BIGEDIT) you can only edit YOUR items – so Directus looks for the "magic owner column" (which is now called `user_create_column`) but it's empty, so it throws an error.

But you're getting an error with BIGEDIT, which doesn't make as much sense since you should be able to delete ANY records.

**Comment by WellingGuzman** [comment]
I have a question on this, what happens if the table does not have owner all the users won't have `BIG` permission, so is this error ok?

**Comment by benhaynes** [comment]
With `BIG` permissions things should *always* work (doesn't need an *owner column* set) – since they mean you have permission for all items. 

There should only be an error if you only have `EDIT` (not `BIGEDIT`) since then Directus needs to know who created each item. That way it can check that you're only editing items you created.

**Comment by benhaynes** [comment]
@WellingGuzman You mention this should be all set – I'll close for now, we'll continue to test to see if there are any issues.
