### ISSUE TITLE
Creating new items, draft is default.

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#500]
![screen shot 2014-12-08 at 1 55 50 am](https://cloud.githubusercontent.com/assets/1531291/5335313/5a8e7984-7e7d-11e4-8ede-35a9817cc0b8.png)

**Comment by benhaynes** [comment]
@WellingGuzman Are you still having this problem?

**Comment by WellingGuzman** [comment]
no, this problem was solved this PR#504 and then fixed again with #535.

**Comment by benhaynes** [comment]
good to hear! 
:thumbsup:
