### ISSUE TITLE
Bookmarks/Tabs/Nav Override

### ISSUE THREAD

**Issue by benhaynes** [RNGR/directus6#516]
**Tabs and Bookmarks**: This naming is from when Directus navigation was tab-based. It no longer is, and we want to generalize that language – so all references to links in the sidebar should be called: **nav**

*directus_bookmarks* – is there a reason this shouldn't switch to *directus_snapshots*? Does it hold data other than snapshots?

*directus_tab_privileges* should become *directus_nav_privileges* and its schema should be adjusted:
* **id**: stays the same
* **group_id**: stays the same
* **tab_blacklist**: becomes **nav_blacklist**
* **nav_override**: **NEW COLUMN**, if not NULL (has JSON) then it overrides the bookmarks sections. This gives admins the ability to customize the navigation (order, naming, visibility, etc) for user groups. Here is the format for the JSON:

```
{
	"Office": {
		"About": {
			"path": "/about"
		},
		"Events": {
			"path": "/about"
		}
	},
	"Work": {
		"Case Studios": {
			"path": "/case-studies"
		},
		"Press": {
			"path": "/press"
		}
	}
}
```

This structure fits into the new sidebar design (see below). The reason for objects instead of an array is we might want to extend this to manage icons (or other parameters) in the future.

Here is a quick sketch of the naming convention:
![directus_sidebar_naming](https://cloud.githubusercontent.com/assets/522079/5387313/4ed01294-80a6-11e4-8ba9-e56f9bba515c.gif)

**Comment by WellingGuzman** [comment]
Would this:
```json
{
    "Office": {
        "About": {
            "path": "/about"
        },
        "Events": {
            "path": "/about"
        }
    },
    "Work": {
        "Case Studios": {
            "path": "/case-studies"
        },
        "Press": {
            "path": "/press"
        }
    }
}
```

Turn into:

![screen shot 2015-01-31 at 6 20 29 pm copy](https://cloud.githubusercontent.com/assets/1531291/5990060/cda95942-a976-11e4-9ff2-d3ac138ab946.png)

**Comment by benhaynes** [comment]
Yes, but without the word "TABLES" at the top – it would be up to the admin to decide if that should be there.

**Comment by WellingGuzman** [comment]
This PR, creates the new table column named `nav_override`, replacing `tab` with `nav` is in process, I would wait until DB Changes is done, then change all the code naming with `nav` instead of `tab`

**Comment by benhaynes** [comment]
@WellingGuzman Could we add a "try" to the JSON decode so that if it is malformed we use the default and show a console.log: "The nav override JSON for this user group is malformed – the default nav will be used instead"

**Comment by benhaynes** [comment]
@WellingGuzman Looking good – but all of my links are taking me to **/tables** – any idea why?

**Comment by WellingGuzman** [comment]
@benhaynes oh I'm working on all at the same thing that I don't know at what this got wrong... I sent a PR [#622](https://github.com/RNGR/directus6/issues/622)
