### ISSUE TITLE
Accessing Moment through the global scope.

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#521]
This issue is a reminder of this warning.

`Accessing Moment through the global scope is deprecated, and will be removed in an upcoming release.`

![screen shot 2014-12-10 at 11 43 12 pm](https://cloud.githubusercontent.com/assets/1531291/5388712/634398b6-80c6-11e4-8d59-8f8aeb92d86c.png)

**Comment by benhaynes** [comment]
@WellingGuzman This was a duplicate of issue https://github.com/RNGR/directus6/issues/430 – so I just closed the other one.

**Comment by WellingGuzman** [comment]
@benhaynes I'll close this one, I've experienced this warning anymore. I'll reopen if it happens again.
