### ISSUE TITLE
Add new table to the sidebar

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#530]
Without the need to refresh the page, new tables should appear on the sidebar upon creation.

**Comment by benhaynes** [comment]
@WellingGuzman This is working for new tables made in Directus, but if a table is added in the database directly and you add permissions then it doesn't move into the sidebar until you refresh.

**Comment by WellingGuzman** [comment]
@benhaynes Oh, you're right, so, after you add permission (view at least) it should be moved into the sidebar.
I'll work on that.

**Comment by benhaynes** [comment]
Seems to still have some issues – when toggling VIEW on/off it doesn't seem to work after the first time.

But that's ok... no need to spend more time on this one. Closing and we can re-open if it becomes a more serious issue.

**Comment by WellingGuzman** [comment]
@benhaynes I really didn't work on removing it after view has being off, it slipped my mind, I could work on that, if it's a serious issue, or something you think it really need to be implemented as soon as possible. let me know.

**Comment by WellingGuzman** [comment]
@benhaynes also when you switch `hidden` on/off.
