### ISSUE TITLE
Get rid of one step on the installation

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#533]
I would suggest jump the step of choosing the media url and directory, as right now it can be guessed by the installation, we can just default that to our current default directory `media` and then if the end user want to change that well, change it on the config.

I don't think this would be a choice that would change a lot.

**Comment by benhaynes** [comment]
@WellingGuzman As I mentioned in the comments of the pull-request – if any of the media paths don't exist or aren't writable, then on the confirmation page we should have the following alert text in red:

"The default upload directories are either missing or don't have write permission. You can add these directories/permissions on your server or update the `directus_storage_adapters` table with new paths."

**Comment by WellingGuzman** [comment]
@benhaynes I made a PR (#561) and when there's not `/media` directory or is not writable it put a message under the installation summary above the config message when there's not permission.
![screen shot 2015-01-04 at 2 02 21 pm](https://cloud.githubusercontent.com/assets/1531291/5606869/5791f12c-941a-11e4-8f47-cd98b83381e2.png)

**Comment by benhaynes** [comment]
@WellingGuzman Perfect!
