### ISSUE TITLE
Table with empty permission crash the whole page

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#538]
If you leave a row without any permission value in the `directus_privileges` table it would throw a 500 Internal Server Error and a blank page.

**Comment by benhaynes** [comment]
@WellingGuzman Technically you should not be able to see that page (since you don't have view permission) so this makes sense – but we need to make it friendlier:

**Redirect to the table-listing page with a Directus-style alert: "You do not have permission to view that page or it doesn't exist"**

**Comment by benhaynes** [comment]
Looks good!
