### ISSUE TITLE
Put asterisk on required fields

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#542]
![screen shot 2014-12-19 at 10 47 27 pm](https://cloud.githubusercontent.com/assets/1531291/5513560/2ae25ec8-87d1-11e4-9fc3-80c052766618.png)

**Comment by benhaynes** [comment]
@WellingGuzman Maybe asterisks are not showing up there because it's a system page? I know they work in other places...

**Comment by benhaynes** [comment]
I see asterisks now!
