### ISSUE TITLE
You can still "delete" items you do not have permission

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#543]
You can still "delete" any item even if the group your user is in do not have permission to do it.

**Comment by WellingGuzman** [comment]
This is already done, with the new hard delete feature.

**Comment by benhaynes** [comment]
@WellingGuzman So for now the soft-delete feature is handled by the EDIT permission, not the DELETE permission – correct? I think that makes sense since that's what's actually happening.

**Comment by WellingGuzman** [comment]
Yes, it's what actually happens, but as it a special `EDIT` permission on a single field I think it's better way to be handle by the `DELETE` permission. we can change back this to the previous edit, if you believe this is wrong or it's better to do it with the `EDIT` permission.

I see it this way, without knowing how it works behind the scene, when you give the wrong user a edit permission without knowing it can hide from that data. but maybe it just me.

so should we take this change back?

**Comment by benhaynes** [comment]
@WellingGuzman If you're saying that soft-delete is currently managed by the DELETE permission then let's leave it as is. Having all delete options (soft and hard) managed by the same permission makes sense.
