### ISSUE TITLE
Update tables after permission change

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#544]
After a permission is changed is not reflected until the page is refresh it.

Go to Groups permission change a permission (add) for example, then go back to the table and the permission (UI) still the same.

**Comment by benhaynes** [comment]
@WellingGuzman This works if you add a table through Directus, but not if you add it directly to the database and then change the table permissions to be visible.

**Comment by benhaynes** [comment]
Looks good, I thought there was an issue with adding tables directly, but we can open a new ticket for that if it still exists
