### ISSUE TITLE
Can't select UI images

### ISSUE THREAD

**Issue by benhaynes** [RNGR/directus6#564]
http://directus.rngr.org/tables/arts/21
If you go to this page and click "Directus Files" under Image – it takes you to a file listing page, but there are no checkboxes. And clicking on the images/files no longer select them.

**Comment by benhaynes** [comment]
@WellingGuzman Half of this has been completed, thanks!

There are now checkboxes on the File select, so that's good – but previously the user could click the *entire row* and it would select the file (auto-check the box). Not sure when this was removed, or if it's part of standardization – but it was a useful feature.

**Comment by benhaynes** [comment]
@WellingGuzman Also, there are two other issues:

1. **Not Saving:** Once clicked, save doesn't work. So even if you have an image selected, it won't save back to the UI. Console.log says: "Save" but nothing happens.

2. **Single File:**Also, when coming from a **single** UI field only one file should be selectable. Ideally, when you click the image it should auto-save and return you to the UI.

3. **Multiple Files:** If a UI accepts multiple files then you should click files to select them, then you'd hit the save button ("check") to save into the UI. If the UI has a restriction on how many files it will accept this should be honored by the File Select Overlay.

**Comment by WellingGuzman** [comment]
I do not what happen there, but I'm testing it right now and it does exactly as you said it should behave.

- When I click the row it auto select the file
- Can only select one item on **Single UI**
- Can select multiple items on **Multiple Files**

I haven't tested the UI restriction, because right now I don't know where's that option, I would check later to see where is it and let you know, but the others are working fine, in my local repository.

Try again if still happen Let's see what we can do.

**Comment by benhaynes** [comment]
Interesting, let me make sure my local is up-to-date with cache cleared and I'll test again.

**Comment by benhaynes** [comment]
@WellingGuzman I have updated the remote server with the most recent commits. Does this page work for you?

http://directus.rngr.org/tables/fitness

Clicking "Directus Files" beside "Schedule PDF" opens the list select overlay... but I can't click items, and it doesn't save.

**Comment by WellingGuzman** [comment]
For an Odd reason I had a version with was part updated, but anyway the issue with this wasn't that you cannot select the image it was an missing part of the file verification method. 

I tested and it works and it should work after this PR.

**Comment by benhaynes** [comment]
Lookin good!
