### ISSUE TITLE
Show useful alert if missing directus_tables entry

### ISSUE THREAD

**Issue by benhaynes** [RNGR/directus6#566]
If trying to access a table and it is missing from the `directus_tables` table you currently get a **server error 500**. Instead, a console log or Directus alert should say:

"The table you are attempting to access (*TABLENAME*) is missing from `directus_tables` and must be configured"

**Comment by WellingGuzman** [comment]
@benhaynes does this still happening? I can access tables that are missing from the `directus_tables` and I can still see the page with no error, either in settings and listing.

**Comment by benhaynes** [comment]
No, this doesn't seem to be happening anymore. I'll close, and reopen if anything comes up.
