### ISSUE TITLE
Hit enter to insert not working

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#577]
If you try to insert a new value by hit enter it will reload the page but wont insert the value.

**Comment by benhaynes** [comment]
@WellingGuzman insert a value where? In an input on the edit page?

**Comment by WellingGuzman** [comment]
Exactly in a Input on a edit page, it submits the form, but as right now we are not handling submit, sot it wont do nothing rather than reload the page.

**Comment by WellingGuzman** [comment]
will remain closed, in case another similar issue occur I'll open it.
