### ISSUE TITLE
Setting table privileges saves partial permissions

### ISSUE THREAD

**Issue by benhaynes** [RNGR/directus6#583]
Using the UI to save full permissions saves:

**add,bigedit,bigdelete,bigview**

Instead of:

**add,edit,bigedit,delete,bigdelete,alter,view,bigview**

Either the framework should respect the higher permission, or it should save the full set of permissions within `directus_privileges`

**Comment by benhaynes** [comment]
Here is an example of an error from the shorter permissions.

![screen shot 2015-01-15 at 2 06 45 pm](https://cloud.githubusercontent.com/assets/522079/5764742/6ec57142-9cc2-11e4-88f4-7a0f25a3ce37.png)

**Comment by WellingGuzman** [comment]
It should always have `alter` permission?

**Comment by benhaynes** [comment]
@WellingGuzman You're right! It is fine that this is hardcoded – but we need to check to make sure the current user is an **Admin**.

**Comment by benhaynes** [comment]
Perfection...
