### ISSUE TITLE
Sorting string-value columns unexpected results

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#591]
Sorting string-value column results on a unexpected results, in other words is not sorting correctly.

Edit: This is only happening on many to many tableview.

**Comment by Zaelot** [comment]
Sorting seems to still have some issues. For example, in M2O if you start with `{{id}}` in _Visible Column Template_ it'll sort the dropdown values disregarding the numerical value (first everything starting with 0, then with 1, then with 2 and so on).
(Would also be nice to be able to sort the values by a non-visible column.)
  

![image](https://user-images.githubusercontent.com/2608781/29625938-ddec1e8e-8835-11e7-91c5-5f20a3c4054d.png)

**Comment by WellingGuzman** [comment]
Hey @Zaelot Where is the sorting happening? on the interface or table or api?

**Comment by Zaelot** [comment]
Hi @WellingGuzman! In the interface. I tested with the API and it works correctly there, with sorting affecting the actual order. It seems that in the interface it sorts them by the string, and that doesn't check whether the number continues. (Noticed at first when the dropdown contents were sorted by alphabetical order, then tried to include both Id and Sorting in front, but as you can see, that didn't quite work out either.)

  

(Unrelated question: Are we supposed to be able to add items to Dropdown Enum after it's creation? UI let's you edit the values - in a field still misnamed as "Length", but saving causes an error. Current solution being re-creating the field.)

**Comment by WellingGuzman** [comment]
The problem still that it will translate to a string so it won't be sorted properly as you should expect, We are going to check this issue and get it resolved in some way or another.

can you provide a steps on that ticket, or create a new one specifying all the steps logs, screenshot, etc. 

Thanks
