### ISSUE TITLE
Missing sort column query error

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#597]
This is happening lately at random. I would post more notes on this.

![screen shot 2015-01-20 at 11 30 03 pm](https://cloud.githubusercontent.com/assets/1531291/5831242/76259596-a0fc-11e4-8f5c-5ee570ff6394.png)

**Comment by benhaynes** [comment]
@WellingGuzman On deirectus.rngr.org? Which page? Does that table have an active and sort column?

**Comment by WellingGuzman** [comment]
I was on the Dinning page, but that's the point is trying to get an non-existing column, don't know why yet why is this happening and how because it's random. I'd take a deep look later and fix it.

**Comment by benhaynes** [comment]
Will re-open if appears again
