### ISSUE TITLE
URL Ending with trailing slash return not found page

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#635]
going to: `directus.site/tables/accommodations` works.
going to: `directus.site/tables/accommodations/` does not work display a not found page.

**Comment by WellingGuzman** [comment]
@benhaynes I have to ask first, does this need to be fixed? I do not see the point to treat this differently, both url should act as the same.

**Comment by benhaynes** [comment]
@WellingGuzman I agree – they should be the same. I think this was part of the SLIM routing... since the slash meant to look for an ID or NEW in the URL... but the routes should still work with what you've added here.
