### ISSUE TITLE
Save scroll position for each page/overlay

### ISSUE THREAD

**Issue by benhaynes** [RNGR/directus6#646]
This happens in a few places, but one in particular needs to be fixed:

When editing an item, some UIs (many-to-many, choose file, etc) have an overlay for selecting other, related, items. After choosing/saving items from the overlay you go back to the edit page... but are taken to the top of the page (not original scroll position).

We should be saving the scroll position somehow (data attribute?) for each page/overlay, so that when you return to that page you're in the same place. This needs to be saved for **each** page/overlay (not just one global variable) since sometimes you can be several overlays deep.

@WellingGuzman Does this make sense? Any thoughts?

**Comment by WellingGuzman** [comment]
@benhaynes I submitted a PR #647

**Comment by benhaynes** [comment]
This works perfectly, thanks @WellingGuzman 

Is it possible to include the same feature on other pages (non-overlay)? There are two places I think this would be useful:

**Listing Pages**: If you go from a longer, scrolling listing page (or the *Files* page) to an edit page, then save the item... you go back to the item listing page, but back at the top. Would there be a way to return the user to the scroll position within the item listing? Also, if we could briefly highlight the *item you're coming from* on the listing page... that would also resolve https://github.com/RNGR/directus6/issues/109

1. On Projects Listing Page
2. Scroll down to lower item
3. Click on lower item to edit
4. Edit the item and hit "save"
5. Directus returns you to the item listing page, scrolled to where you were before
6. (Bonus) Briefly highlighting the item you were editing for reference (there is an existing highlight/hover color we can use)

**Navigation**: If the list of tables in the sidebar is taller than the viewport you need to scroll down to see the lower tables/navigation. Currently, if you click on a nav item (when scrolled down) it navigates you to that page, but also resets your sidebar scroll back to the top. With a longer nav list this would be annoying since you lose track of where you were.

**Comment by WellingGuzman** [comment]
@benhaynes let me work something out for this one.

**Comment by benhaynes** [comment]
@WellingGuzman It seems to be scrolling to the right place now, but maybe the re-render is still causing some issues. The FlashRow doesn't seem to be happening, so maybe that's the render?

**Comment by WellingGuzman** [comment]
@benhaynes is the flashRow not working for you? can you give me a step by step where it does not trigger for you?

**Comment by benhaynes** [comment]
@WellingGuzman 

1. Click a into an item from the listing page
2. Edit that item
3. Hit Save
4. It takes me back to the listing page (with the correct scroll!)
**5. But it does not highlight or flash the row I was just editing**

I assume that is what RowFlash is suppose to do?

**Comment by WellingGuzman** [comment]
@benhaynes Oh, you are right, Thanks for pointing that out, I tested it again, and it does flash the row. but at the same time, _after the item is saved, not when you go back from the item_, the list re render and the flash goes away at that time.

I'd work on something here.

**Comment by benhaynes** [comment]
Perfection.
