### ISSUE TITLE
Track additional data in directus_activity

### ISSUE THREAD

**Issue by benhaynes** [RNGR/directus6#653]
In addition to the data currently being tracked, we need to save the following for each activity item:

* parent_table — We're saving the ID, but this is useless without knowing the table it belongs to
* user_agent — We should track the browser, version and OS in a field so we can troubleshoot front-end issues

**These are less important, and not urgent:**
* ip — this seems to be saving the same IP address, could it be pulling the server IP instead of the user IP? Maybe this is because I'm looking at an install that is setup on a VPN?
* identifier — this doesn't always seem to save. Basically this field should save the data from the primary field of that record for easy identification

**Comment by WellingGuzman** [comment]
This two PR #661 #665 would fixed/implemented this issue. although the ip being the same I think it because the VPN, the same way when you it used on localhost.

**Comment by benhaynes** [comment]
@WellingGuzman That makes sense... I'll test later today, but this should be good to go!

**Comment by benhaynes** [comment]
Good to go, indeed!
