### ISSUE TITLE
Table prefix it's not being used to create tables

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#655]
When installing directus, there's a field to specify whether or not a prefix it's going to be used for the tables during installation, but it's not actually used.

**Comment by benhaynes** [comment]
@WellingGuzman I don't think this is a very useful feature given that most Directus installs will use a dedicated database. Let's comment out this feature from the Installation file and close the issue. We can re-open in later versions.

**Comment by benhaynes** [comment]
Nice. I don't think the "prefix" would be used too often, so it's good to avoid the added complexity until it's more requested.
