### ISSUE TITLE
Is there are reason to mark table (name) starting with 0 as featured?

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#681]
@benhaynes Tables name starting with zero are styled as bold and marked as featured, is there a reason for this behavior? 
![screen shot 2015-03-04 at 3 11 40 am](https://cloud.githubusercontent.com/assets/1531291/6479487/68755120-c21c-11e4-9b62-733d6886ddc4.png)

**Comment by benhaynes** [comment]
@WellingGuzman there was a feature built into Directus to "favorite" important tables – this was most useful when there were many tables to make it easier to find the most used ones.

We can remove that now since we allow for customizable sidebars and have "bookmarks" for the edit pages.
