### ISSUE TITLE
navigation scroll get lost after re-render of the whole page.

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/directus6#692]
Part of the issue #646 

This is a issue that should be called why re render the whole page instead the content that's being changed?

For now I only focused the issue on the fact that it breaks the saved scroll on navigation.

**Comment by benhaynes** [comment]
@WellingGuzman Should we close this issue or is there more to be done?

**Comment by WellingGuzman** [comment]
@benhaynes yes we can close it, this was the only one. (at least the only one I experienced) so we should be good.

**Comment by benhaynes** [comment]
Awesome.
